//!
//! Rust Firebird Client
//!
//! Example of select
//!
//! You need create a database with this table:
//! create table test (col_a int generated by default as identity, col_b float, col_c varchar(10));
//!
//! You can use the insert example to populate
//! the database ;)
//!

use rsfbclient::{Connection, FbError};

fn main() -> Result<(), FbError> {
    let conn = Connection::open("localhost", 3050, "examples.fdb", "SYSDBA", "masterkey")?;

    let tr = conn.transaction()?;

    let rows = tr
        .prepare("select col_a, col_b, col_c from test")?
        .query_simple()?
        .into_iter();

    println!("| col_a | col_b | col_c   |");
    println!("| ----- | ----- | ------- |");
    for row in rows {
        let (col_a, col_b, col_c): (i32, f32, String) = row?;

        println!("| {:^5} | {:^5} | {:7} |", col_a, col_b, col_c);
    }

    Ok(())
}
